su_challenge:
  outputs:
    dev:
      dataset: dbt_sumup
      job_execution_timeout_seconds: 300
      keyfile: /Users/carloscalisi/Documents/sumup-take-home-test-account-creds.json
      job_retries: 1
      location: US
      method: service-account
      priority: interactive
      project: sumup-take-home-test
      threads: 1
      type: bigquery
  target: dev
